CREATE TABLE VEHICLE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BRAND VARCHAR(50),
    MODEL VARCHAR(50),
    ENGINE VARCHAR(50),
    MAKE_YEAR INT
);

CREATE TABLE OPERATION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BRAND VARCHAR(50),
    MODEL VARCHAR(50),
    ENGINE VARCHAR(50),
    YEAR_START INT,
    YEAR_END INT,
    DISTANCE_START DOUBLE,
    DISTANCE_END DOUBLE,
    NAME VARCHAR(100),
    APPROX_COST DOUBLE,
    DESCRIPTION VARCHAR(255),
    TIME INT
);
